# Generated by Django 5.1.4 on 2025-02-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='children', to='users.student'),
        ),
    ]
