# Generated by Django 5.1.4 on 2025-02-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Group',
        ),
    ]
